#შეადარეთ 10 სტრინგი ერთმანეთს. მაგ( "Hello" == "HelloWorld" )
print("hello" == "helloworld")
print("aleksandre" != "sirbiladze")
print("name" < "surname")
print("number" == "number")
print("laptop" <= "compiuter")
print("dog" == "cat")
print("lion" >= "tigger")
print("pencil" < "pencilcase")
print("game" == "book")
print("gift" >= "toy")